Сделал ui для проекта на этапе подачи заявки
RushanCources/Project-38 pull request #123
Opened 2023-07-08 20:30 UTC by cbytl1

конечно возможны некие изменения в будущем, это считай первая версия

2023-07-20 14:09 UTC, Teri-IM requested changes
Перед или после слияния нужно сделать ещё одну ветку, т.к. работа над ui в projects_page ещё не окончена

2023-07-20 14:09 UTC, Teri-IM commented on portal/media/avatars/t2CNeSsPLNA_SaHWFrb.jpg
Аватарки стоит добавить в gitignore

2023-07-21 19:12 UTC, cbytl1 commented
после слияния сделаешь себе ветку. Ты там вообще не с объявлениями разве работаешь?

2023-07-21 19:20 UTC, Teri-IM approved these changes

2023-07-21 19:22 UTC, cbytl1 commented on portal/media/avatars/t2CNeSsPLNA_SaHWFrb.jpg
есть такое, сейчас добавлю

2023-07-21 19:27 UTC, Teri-IM approved these changes

2023-07-21 19:29 UTC, merged